language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: mahnunchik@gmail.com
  api_key:
    secure: kMb0zTAOXjCBuH/oSGgVCBOWgV7Ka4W2Dhnohex2xo9w6Y8PTZ3PSAcP9WyAafBxTfgW+1mcz3zhleSfpLb+tAz/o7r1Eq/W6s8kNeF/d5K+HZTKLih6EE/hpNnQKTeIdn1gsJ6pPp1d5F+9xaGy0a6an0df/JDKpfnym6jllGc=
  on:
    tags: true
    repo: mahnunchik/mag-fallback
    all_branches: true
